# Generated by Django 6.1.1 on 2026-09-10 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('aptitude', 'Aptitude'), ('managerial', 'Managerial'), ('other', 'Other')], max_length=20)),
                ('interviewer', models.CharField(blank=True, max_length=150)),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.jobapplication')),
            ],
            options={
                'ordering': ['interview_date', 'interview_time'],
                'indexes': [models.Index(fields=['interview_date', 'status'], name='interviews__intervi_996e0c_idx')],
            },
        ),
    ]
